version: '3.8'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  chatapplication:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
